#!/usr/bin/env python3
"""
Setup script for ScryptBot .env file
This script helps you create your .env file with Twitter API credentials
"""

import os

def create_env_file():
    """Create .env file with user input"""
    
    print("🐦 ScryptBot Twitter API Setup")
    print("=" * 50)
    print("This script will help you create your .env file with Twitter API credentials.")
    print("Make sure you have your Twitter API keys ready!")
    print()
    
    # Check if .env already exists
    if os.path.exists('.env'):
        response = input("A .env file already exists. Overwrite it? (y/n): ")
        if response.lower() != 'y':
            print("Setup cancelled.")
            return
    
    print("Please enter your Twitter API credentials:")
    print()
    
    # Get API credentials from user
    bearer_token = input("Bearer Token: ").strip()
    api_key = input("API Key (Consumer Key): ").strip()
    api_secret = input("API Key Secret (Consumer Secret): ").strip()
    access_token = input("Access Token: ").strip()
    access_token_secret = input("Access Token Secret: ").strip()
    
    # Validate that all fields are filled
    if not all([bearer_token, api_key, api_secret, access_token, access_token_secret]):
        print("❌ Error: All fields are required!")
        return
    
    # Create .env content
    env_content = f"""# ScryptBot Modern - Environment Configuration
# Generated by setup script

# =============================================================================
# TWITTER API CONFIGURATION (Required)
# =============================================================================

# Bearer Token for Twitter API v2 (Required for streaming)
TWITTER_BEARER_TOKEN={bearer_token}

# API Key and Secret (Required for posting tweets)
TWITTER_API_KEY={api_key}
TWITTER_API_SECRET={api_secret}

# Access Token and Secret (Required for posting tweets)
TWITTER_ACCESS_TOKEN={access_token}
TWITTER_ACCESS_TOKEN_SECRET={access_token_secret}

# =============================================================================
# GOOGLE CLOUD CONFIGURATION (Optional - for enhanced analysis)
# =============================================================================

# Path to Google Cloud service account credentials JSON file
# Get this from: https://console.cloud.google.com/apis/credentials
GOOGLE_APPLICATION_CREDENTIALS=path/to/your/credentials.json

# =============================================================================
# TRADING CONFIGURATION
# =============================================================================

# Set to YES to enable real money trading (NOT RECOMMENDED for testing)
# Set to NO for simulation mode (RECOMMENDED)
USE_REAL_MONEY=NO

# Polygon API key for additional market data (Optional)
# Get this from: https://polygon.io/
POLYGON_API_KEY=your_polygon_api_key_here

# =============================================================================
# APPLICATION SETTINGS
# =============================================================================

# Enable debug mode for detailed logging
DEBUG=NO

# Run in test mode with sample data (Set to NO for real tweets)
TEST_MODE=NO

# Logging level: DEBUG, INFO, WARNING, ERROR
LOG_LEVEL=INFO

# Send logs to Google Cloud Logging (requires Google Cloud setup)
LOGS_TO_CLOUD=NO

# =============================================================================
# WEB INTERFACE SETTINGS (Optional)
# =============================================================================

# Host for web interface
WEB_HOST=0.0.0.0

# Port for web interface
WEB_PORT=8080

# =============================================================================
# DATABASE SETTINGS (Optional)
# =============================================================================

# Database URL for storing tweet history and portfolio data
# Default: SQLite database in project directory
DATABASE_URL=sqlite:///scryptbot.db

# =============================================================================
# EMAIL NOTIFICATIONS (Optional)
# =============================================================================

# Enable email notifications
ENABLE_EMAIL_NOTIFICATIONS=NO

# SMTP server settings
EMAIL_SMTP_SERVER=smtp.gmail.com
EMAIL_SMTP_PORT=587
EMAIL_USERNAME=your_email@gmail.com
EMAIL_PASSWORD=your_app_password_here
EMAIL_TO=recipient@example.com
"""
    
    # Write to .env file
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        
        print()
        print("✅ .env file created successfully!")
        print()
        print("Next steps:")
        print("1. Run: python main_modern.py")
        print("2. Check the logs for any errors")
        print("3. Monitor scryptbot.log for real-time processing")
        print()
        print("Your ScryptBot is now ready to monitor real X tweets! 🚀")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")

def main():
    """Main function"""
    try:
        create_env_file()
    except KeyboardInterrupt:
        print("\nSetup cancelled.")
    except Exception as e:
        print(f"❌ Error: {e}")

if __name__ == "__main__":
    main() 